server:
  port: 80

spring:
  jpa:
    database: mysql
    show-sql: true
#    properties:
#      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf8
    username: root
    password: Zheng1234


  thymeleaf:
    cache: false

